apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: kaniko-build
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/{ GitHub username }/helloworld-knative-gke
      revision: master
  template:
    name: kaniko
    arguments:
      - name: IMAGE
        value: docker.io/{ Docker Hub username }/helloworld-go
  timeout: 10m