apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        metadata:
          name: kaniko-build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/scranton/helloworld-knative-gke
              revision: master
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: docker.io/scottcranton/helloworld-go
          timeout: 10m
      revisionTemplate:
        spec:
          container:
            image: docker.io/scottcranton/helloworld-go
            imagePullPolicy: Always
            env:
              - name: TARGET
                value: "Go Sample v1"